# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 72387426cc191ea4cce5db20f1d187be4f4b848c8b93d5467973053eaac1ae1a6807a326fdde9f49f634e675fed564dae1fe7f899d7bbbdaf95bc172b86cdbbf

test:
  secret_key_base: a33e7493ccf473df6fd4729b7ed9c5c87d9ebb90bfdd738acd5f237cb18862e6ff0a774342a898543f8c6c6dc0c537f6556cf649e4951d4edcd7530585b07fa7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
